### ISSUE TITLE
VendorGen never ends

### ISSUE THREAD

**Issue by kamronbatman** [modernuo/ModernUO#76]
Using [vendorgen never ends. After a world save it finishes and is incomplete.
No crash.

**Comment by 3HMonkey** [comment]
Vendorgen is an old command of RunUO.  It generates vendors based on display cases and floor plans. Means it analyzes the map files and so on and is slow as hell. Btw because of these nested loops and the "CheckPoint" methode which also contains loops etc. etc.

![grafik](https://user-images.githubusercontent.com/4610892/72716845-37b35980-3b73-11ea-8d23-b61da0bde45f.png)

ServUO is doing it by using XML-Spawners, so they flagged that command as deprecated in 2016.

**Comment by kamronbatman** [comment]
I wouldn't mind a json spawner...
