### ISSUE TITLE
Armor hue reverts to hue = 0 at server restart

### ISSUE THREAD

**Issue by Arthrutus** [modernuo/ModernUO#808]
Armor that is dyed (e.g. armor of fortune or any type of armor with hue != 0) will revert to hue = 0 when the server is restarted. Weapons and clothing are unaffected by this.

**Comment by kamronbatman** [comment]
Looks like the issue is here:
https://github.com/modernuo/ModernUO/blob/990d151ef302b70bb21d4b3e94b8df73ad7c9ef8/Projects/UOContent/Items/Armor/BaseArmor.cs#L290

I'll need to change Codegen to serialize/deserialize the `field` and not the `property`. This is a little tricky since I rely on the same code path to handle migrations and deserialization.

https://github.com/modernuo/ModernUO/blob/990d151ef302b70bb21d4b3e94b8df73ad7c9ef8/Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.DeserializeMethod.cs#L171
Currently we rely on the SerializableProperty (essentially the same view used to do migrations), which has the property name.

I'll have to generalize this more and create an array of SerializeProperty structs that have the field as the Name instead of the property.
