### ISSUE TITLE
Using some skills when character is invisible

### ISSUE THREAD

**Issue by romanlysenko** [modernuo/ModernUO#864]
Is it correct that when a character is invisible he can use some skills without leaving invisibility? For example, such skills as ArmsLore, AnimalLore, etc. can be used while remaining invisible! Maybe I'm wrong, probably this mechanic from the official server. But I think this is not correct. 

By the way, being in invisibility and using the DetectHidden skill, I will never find myself.

Maybe is it better to add a check to the `public static TimeSpan OnUse(Mobile m) {...}` method in folder/files: UOContent/Skills/*.cs? For example, the `RevealingAction()` method, how it is done in AnimalTiming?

**Comment by Arthrutus** [comment]
Yes. You can download the UO client from uo.com and test things on the test shard. According to OSI, using skills, such as armslore and animal lore, do not reveal the player. Additionally, detect hidden does not work on the player (Which makes sense since the player is self-aware). MUO strives to follow OSI standards.

**Comment by romanlysenko** [comment]
I'm understood, thank you! Just wanted to make sure it was right ;)
